###
GET http://localhost:8080/api/admin/allFonts

###
GET http://localhost:8080/api/admin/allPreference

###
GET http://localhost:8080/api/admin/allPicture

###
GET http://localhost:8080/api/v2/media/display/5fc601dcf1782d1bbd4d4e26

###
GET http://localhost:8080/api/v2/media/download/5fc4e30a62d0f53bac878fbd
